<script setup>
import { ref } from 'vue'
const months = ref([
  {
    name: 'January',
    days: 31,
    rows: 5,
    dates: [
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'February',
    days: 29,
    rows: 5,
    dates: [
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'March',
    days: 31,
    rows: 6,
    dates: [
      { number: 25, events: [], dayIsInThisMonnth: false },
      { number: 26, events: [], dayIsInThisMonnth: false },
      { number: 27, events: [], dayIsInThisMonnth: false },
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false },
      { number: 4, events: [], dayIsInThisMonnth: false },
      { number: 5, events: [], dayIsInThisMonnth: false },
      { number: 6, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'April',
    days: 30,
    rows: 5,
    dates: [
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false },
      { number: 4, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'May',
    days: 31,
    rows: 5,
    dates: [
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'June',
    days: 30,
    rows: 6,
    dates: [
      { number: 26, events: [], dayIsInThisMonnth: false },
      { number: 27, events: [], dayIsInThisMonnth: false },
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false },
      { number: 4, events: [], dayIsInThisMonnth: false },
      { number: 5, events: [], dayIsInThisMonnth: false },
      { number: 6, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'July',
    days: 31,
    rows: 5,
    dates: [
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'August',
    days: 31,
    rows: 5,
    dates: [
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [{ id: 1, name: 'Pouyan Birthday' }], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'September',
    days: 30,
    rows: 5,
    dates: [
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false },
      { number: 4, events: [], dayIsInThisMonnth: false },
      { number: 5, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'October',
    days: 31,
    rows: 5,
    dates: [
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false }
    ]
  },
  {
    name: 'November',
    days: 30,
    rows: 5,
    dates: [
      { number: 27, events: [], dayIsInThisMonnth: false },
      { number: 28, events: [], dayIsInThisMonnth: false },
      { number: 29, events: [], dayIsInThisMonnth: false },
      { number: 30, events: [], dayIsInThisMonnth: false },
      { number: 31, events: [], dayIsInThisMonnth: false },
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true }
    ]
  },
  {
    name: 'December',
    days: 31,
    rows: 5,
    dates: [
      { number: 1, events: [], dayIsInThisMonnth: true },
      { number: 2, events: [], dayIsInThisMonnth: true },
      { number: 3, events: [], dayIsInThisMonnth: true },
      { number: 4, events: [], dayIsInThisMonnth: true },
      { number: 5, events: [], dayIsInThisMonnth: true },
      { number: 6, events: [], dayIsInThisMonnth: true },
      { number: 7, events: [], dayIsInThisMonnth: true },
      { number: 8, events: [], dayIsInThisMonnth: true },
      { number: 9, events: [], dayIsInThisMonnth: true },
      { number: 10, events: [], dayIsInThisMonnth: true },
      { number: 11, events: [], dayIsInThisMonnth: true },
      { number: 12, events: [], dayIsInThisMonnth: true },
      { number: 13, events: [], dayIsInThisMonnth: true },
      { number: 14, events: [], dayIsInThisMonnth: true },
      { number: 15, events: [], dayIsInThisMonnth: true },
      { number: 16, events: [], dayIsInThisMonnth: true },
      { number: 17, events: [], dayIsInThisMonnth: true },
      { number: 18, events: [], dayIsInThisMonnth: true },
      { number: 19, events: [], dayIsInThisMonnth: true },
      { number: 20, events: [], dayIsInThisMonnth: true },
      { number: 21, events: [], dayIsInThisMonnth: true },
      { number: 22, events: [], dayIsInThisMonnth: true },
      { number: 23, events: [], dayIsInThisMonnth: true },
      { number: 24, events: [], dayIsInThisMonnth: true },
      { number: 25, events: [], dayIsInThisMonnth: true },
      { number: 26, events: [], dayIsInThisMonnth: true },
      { number: 27, events: [], dayIsInThisMonnth: true },
      { number: 28, events: [], dayIsInThisMonnth: true },
      { number: 29, events: [], dayIsInThisMonnth: true },
      { number: 30, events: [], dayIsInThisMonnth: true },
      { number: 31, events: [], dayIsInThisMonnth: true },
      { number: 1, events: [], dayIsInThisMonnth: false },
      { number: 2, events: [], dayIsInThisMonnth: false },
      { number: 3, events: [], dayIsInThisMonnth: false },
      { number: 4, events: [], dayIsInThisMonnth: false }
    ]
  }
])

const daySelected = ref(new Date().getDate())

const currentMonth = ref(new Date().getMonth())

function changeMonth(direction) {
  if (direction === 'next' && currentMonth.value < 11) {
    currentMonth.value++
    daySelected.value = 1
  } else if (direction === 'perv' && currentMonth.value > 0) {
    currentMonth.value--
    daySelected.value = 1
  }
}

function changeDay(day) {
  daySelected.value = day
}
</script>
<template>
  <div id="container">
    <div class="calender">
      <Calender
        :months="months"
        :daySelected="daySelected"
        :currentMonth="currentMonth"
        @changeMonth="changeMonth"
        @changeDay="changeDay"
      />
    </div>
    <div class="create-event">
      <CreateEvent :months="months" :daySelected="daySelected" :currentMonth="currentMonth" />
    </div>
  </div>
</template>
<style>
#container {
  display: flex;
  justify-content: flex-start;
}

.create-event {
  width: 20vw;
  height: 90vh;
  order: 1;
}
.calender {
  height: 90vh;
  width: 80vw;
  order: 2;
}
</style>
